---
- name: copy ollama models to a temporary directory if it exists
  hosts: ai
  become: yes

  tasks:
    - name: check if the /tmp/models directory exists
      ansible.builtin.stat:
        path: /tmp/models
      register: models_dir_stat

    - name: copy models from /usr/share/ollama/.ollama/models/ to /tmp/models/
      ansible.builtin.copy:
        src: /usr/share/ollama/.ollama/models/
        dest: /tmp/models/
        # Use remote_src to indicate that the source files are on the target machine
        remote_src: yes
      when: models_dir_stat.stat.exists and models_dir_stat.stat.isdir