---
- name: setup webserver
  hosts: webservers
  become: true
  tasks:

    - name: apache installed
      ansible.builtin.apt:
        name: apache2
        update_cache: true
        state: latest

    - name: custom index.html
      ansible.builtin.copy:
        dest: "/var/www/html/index.html"
        content: |
          Custom Web Page

    - name: enable ssl module
      ansible.builtin.command: a2enmod ssl
      args:
        creates: /etc/apache2/mods-enabled/ssl.load

    - name: enable mod_rewrite module
      ansible.builtin.command: a2enmod rewrite
      args:
        creates: /etc/apache2/mods-enabled/rewrite.load

    - name: a2ensite default-ssl
      command: a2ensite default-ssl

    - name: apache2 service enabled
      ansible.builtin.service:
        name: apache2
        enabled: true
        state: restarted
